use crate::domains::item::{Item, Purpose};

// The item repository.
#[derive(Debug)]
pub struct Repository {
    items: [Item; 168],
}

// Repository enumerated errors.
#[derive(Debug)]
pub enum Error {
    NotFound,
}

// Repository implementation.
impl Repository {
    // Creates a new instance of a item repository.
    pub fn new() -> Self {
        let items: [Item; 168] = [
            Item::new("Potion", Purpose::Restorative),
            Item::new("Potion+", Purpose::Restorative),
            Item::new("Hi-Potion", Purpose::Restorative),
            Item::new("Hi-Potion+", Purpose::Restorative),
            Item::new("X-Potion", Purpose::Restorative),
            Item::new("Mega-Potion", Purpose::Restorative),
            Item::new("Phoenix Down", Purpose::Refinement),
            Item::new("Mega Phoenix", Purpose::Refinement),
            Item::new("Elixir", Purpose::ForbiddenMedicine),
            Item::new("Megalixir", Purpose::ForbiddenMedicine),
            Item::new("Antidote", Purpose::StatusRecovery),
            Item::new("Soft", Purpose::StatusRecovery),
            Item::new("Eye Drops", Purpose::StatusRecovery),
            Item::new("Echo Screen", Purpose::StatusRecovery),
            Item::new("Holy Water", Purpose::StatusRecovery),
            Item::new("Remedy", Purpose::StatusRecovery),
            Item::new("Remedy+", Purpose::StatusRecovery),
            Item::new("Hero-trial", Purpose::Invincibility),
            Item::new("Hero", Purpose::Invincibility),
            Item::new("Holy War-trial", Purpose::Invincibility),
            Item::new("Holy War", Purpose::Invincibility),
            Item::new("Shell Stone", Purpose::SpellStones),
            Item::new("Protect Stone", Purpose::SpellStones),
            Item::new("Aura Stone", Purpose::SpellStones),
            Item::new("Death Stone", Purpose::SpellStones),
            Item::new("Holy Stone", Purpose::SpellStones),
            Item::new("Flare Stone", Purpose::SpellStones),
            Item::new("Meteor Stone", Purpose::SpellStones),
            Item::new("Ultima Stone", Purpose::SpellStones),
            Item::new("Gysahl Greens", Purpose::GFSummon),
            Item::new("Phoenix Pinion", Purpose::GFSummon),
            Item::new("Friendship", Purpose::GFSummon),
            Item::new("Tent", Purpose::Shelters),
            Item::new("Pet House", Purpose::Shelters),
            Item::new("Cottage", Purpose::Shelters),
            Item::new("G-Potion", Purpose::GFRecovery),
            Item::new("G-Hi-Potion", Purpose::GFRecovery),
            Item::new("G-Mega-Potion", Purpose::GFRecovery),
            Item::new("G-Returner", Purpose::GFRecovery),
            Item::new("Rename Card", Purpose::RenameCard),
            Item::new("HP-J Scroll", Purpose::GFAbility),
            Item::new("Str-J Scroll", Purpose::GFAbility),
            Item::new("Vit-J Scroll", Purpose::GFAbility),
            Item::new("Mag-J Scroll", Purpose::GFAbility),
            Item::new("Spr-J Scroll", Purpose::GFAbility),
            Item::new("Luck-J Scroll", Purpose::GFAbility),
            Item::new("Aegis Amulet", Purpose::GFAbility),
            Item::new("Elem Atk", Purpose::GFAbility),
            Item::new("Elem Guard", Purpose::GFAbility),
            Item::new("Status Atk", Purpose::GFAbility),
            Item::new("Status Guard", Purpose::GFAbility),
            Item::new("Rosetta Stone", Purpose::GFAbility),
            Item::new("Magic Scroll", Purpose::CommandAbility),
            Item::new("GF Scroll", Purpose::CommandAbility),
            Item::new("Draw Scroll", Purpose::CommandAbility),
            Item::new("Item Scroll", Purpose::CommandAbility),
            Item::new("Gambler Spirit", Purpose::CommandAbility),
            Item::new("Healing Ring", Purpose::CommandAbility),
            Item::new("Phoenix Spirit", Purpose::CommandAbility),
            Item::new("Med Kit", Purpose::CommandAbility),
            Item::new("Bomb Spirit", Purpose::CommandAbility),
            Item::new("Hungry Cookpot", Purpose::CommandAbility),
            Item::new("Meg's Amulet", Purpose::CommandAbility),
            Item::new("Stell Pipe", Purpose::GFEnhancement),
            Item::new("Star Fragment", Purpose::GFEnhancement),
            Item::new("Energy Crystal", Purpose::GFEnhancement),
            Item::new("Samantha Soul", Purpose::GFEnhancement),
            Item::new("Healing Mail", Purpose::GFEnhancement),
            Item::new("Silver Sail", Purpose::GFEnhancement),
            Item::new("Gold Armor", Purpose::GFEnhancement),
            Item::new("Diamond Armor", Purpose::GFEnhancement),
            Item::new("Regen Ring", Purpose::CharacterAbility),
            Item::new("Giant's Ring", Purpose::CharacterAbility),
            Item::new("Gaea's Ring", Purpose::CharacterAbility),
            Item::new("Strength Love", Purpose::CharacterAbility),
            Item::new("Power Wrist", Purpose::CharacterAbility),
            Item::new("Hyper Wrist", Purpose::CharacterAbility),
            Item::new("Turtle Shell", Purpose::CharacterAbility),
            Item::new("Orihalcon", Purpose::CharacterAbility),
            Item::new("Adamantine", Purpose::CharacterAbility),
            Item::new("Rune Armlet", Purpose::CharacterAbility),
            Item::new("Force Armlet", Purpose::CharacterAbility),
            Item::new("Magic Armlet", Purpose::CharacterAbility),
            Item::new("Circlet", Purpose::CharacterAbility),
            Item::new("Hypno Crown", Purpose::CharacterAbility),
            Item::new("Royal Crown", Purpose::CharacterAbility),
            Item::new("Jet Engine", Purpose::CharacterAbility),
            Item::new("Rocket Engine", Purpose::CharacterAbility),
            Item::new("Moon Curain", Purpose::CharacterAbility),
            Item::new("Steel Curtain", Purpose::CharacterAbility),
            Item::new("Glow Curtain", Purpose::CharacterAbility),
            Item::new("Accelerator", Purpose::CharacterAbility),
            Item::new("Monk's Code", Purpose::CharacterAbility),
            Item::new("Knight's Code", Purpose::CharacterAbility),
            Item::new("Doc's Code", Purpose::CharacterAbility),
            Item::new("Hundred Needles", Purpose::CharacterAbility),
            Item::new("Three Stars", Purpose::CharacterAbility),
            Item::new("Ribbon", Purpose::CharacterAbility),
            Item::new("Normal Ammo", Purpose::Ammo),
            Item::new("Shotgun Ammo", Purpose::Ammo),
            Item::new("Dark Ammo", Purpose::Ammo),
            Item::new("Fire Ammo", Purpose::Ammo),
            Item::new("Demolition Ammo", Purpose::Ammo),
            Item::new("Fast Ammo", Purpose::Ammo),
            Item::new("AP Ammo", Purpose::Ammo),
            Item::new("Pulse Ammo", Purpose::Ammo),
            Item::new("M-Stone Piece", Purpose::Refinement),
            Item::new("Magic Stone", Purpose::Refinement),
            Item::new("Wizard Stone", Purpose::Refinement),
            Item::new("Ochu Tentacle", Purpose::Refinement),
            Item::new("Healing Water", Purpose::Refinement),
            Item::new("Cockatrice Pinion", Purpose::Refinement),
            Item::new("Zombie Powder", Purpose::Refinement),
            Item::new("Lightweight", Purpose::Refinement),
            Item::new("Sharp Spike", Purpose::Refinement),
            Item::new("Screw", Purpose::Refinement),
            Item::new("Saw Blade", Purpose::Refinement),
            Item::new("Mesmerize Blade", Purpose::Refinement),
            Item::new("Vampire Fang", Purpose::Refinement),
            Item::new("Fury Fragment", Purpose::Refinement),
            Item::new("Betrayal Sword", Purpose::Refinement),
            Item::new("Sleep Powder", Purpose::Refinement),
            Item::new("Life Ring", Purpose::Refinement),
            Item::new("Dragon Fang", Purpose::Refinement),
            Item::new("Spider Web", Purpose::BlueMagic),
            Item::new("Coral Fragment", Purpose::BlueMagic),
            Item::new("Curse Spike", Purpose::BlueMagic),
            Item::new("Black Hole", Purpose::BlueMagic),
            Item::new("Water Crystal", Purpose::BlueMagic),
            Item::new("Missile", Purpose::BlueMagic),
            Item::new("Mystery Fluid", Purpose::BlueMagic),
            Item::new("Running Fire", Purpose::BlueMagic),
            Item::new("Inferno Fang", Purpose::BlueMagic),
            Item::new("Malboro Tentacle", Purpose::BlueMagic),
            Item::new("Whisper", Purpose::BlueMagic),
            Item::new("Laser Cannon", Purpose::BlueMagic),
            Item::new("Barrier", Purpose::BlueMagic),
            Item::new("Power Generator", Purpose::BlueMagic),
            Item::new("Dark Matter", Purpose::BlueMagic),
            Item::new("Bomb Fragment", Purpose::GFCompatibility),
            Item::new("Red Fang", Purpose::GFCompatibility),
            Item::new("Arctic Wind", Purpose::GFCompatibility),
            Item::new("North Wind", Purpose::GFCompatibility),
            Item::new("Dynamo Stone", Purpose::GFCompatibility),
            Item::new("Shear Feather", Purpose::GFCompatibility),
            Item::new("Venom Fang", Purpose::GFCompatibility),
            Item::new("Steel Orb", Purpose::GFCompatibility),
            Item::new("Moon Stone", Purpose::GFCompatibility),
            Item::new("Dino Bone", Purpose::GFCompatibility),
            Item::new("Windmill", Purpose::GFCompatibility),
            Item::new("Dragon Skin", Purpose::GFCompatibility),
            Item::new("Fish Fin", Purpose::GFCompatibility),
            Item::new("Dragon Fin", Purpose::GFCompatibility),
            Item::new("Silence Powder", Purpose::GFCompatibility),
            Item::new("Poison Powder", Purpose::GFCompatibility),
            Item::new("Dead Spirit", Purpose::GFCompatibility),
            Item::new("Chef's Knife", Purpose::GFCompatibility),
            Item::new("Cactus Thorn", Purpose::GFCompatibility),
            Item::new("Shaman Stone", Purpose::GFCompatibility),
            Item::new("Fuel", Purpose::Fuel),
            Item::new("HP Up", Purpose::StatBoosting),
            Item::new("Str Up", Purpose::StatBoosting),
            Item::new("Vit Up", Purpose::StatBoosting),
            Item::new("Mag Up", Purpose::StatBoosting),
            Item::new("Spr Up", Purpose::StatBoosting),
            Item::new("Spd Up", Purpose::StatBoosting),
            Item::new("Luck Up", Purpose::StatBoosting),
            Item::new("LuvLuv G", Purpose::LuvLuvG),
        ];
        Self { items: items }
    }

    // Describe a single item.
    pub fn describe(&self, name: &str) -> Result<Item, Error> {
        let mut item: Option<Item> = None;
        for c in self.items.clone() {
            if c.name == name {
                item = Some(c)
            }
        }
        match item {
            Some(item) => Ok(item),
            None => Err(Error::NotFound),
        }
    }

    // List the items available.
    // TODO: search filter? by purpose?
    pub fn list(&self) -> [Item; 168] {
        self.items.clone()
    }
}
