[package]
name = "cardmod_cli"
version = "1.0.0"
authors = ["iamnande"]
edition = "2021"

[[bin]]
name = "cardmod"

[dependencies]
cardmod = { path = "../lib" }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"